name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: 8l/qbe
        path: ./qbe
        
    - name: Build QBE
      working-directory: ./qbe
      run: make

    - uses: actions/checkout@v4
      with:
        repository: elmvel/Evec-Rust
        path: ./Evec-Rust
        
    - name: Build
      working-directory: ./Evec-Rust
      run: pwd && ls && make debug
      
    - name: Run tests
      working-directory: ./Evec-Rust/tests/
      run: ls .. && echo "=" && ls . && alias qbe=../qbe/obj/qbe && ./rere.py replay test.list
